[package]
name = "exconman"
version = "0.1.0"
authors = ["Abu Khan <cmdwannabe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
regex = "1.4.1"
